environment_version: 1
credentials:
- type: aws
  id: MPMAkOkCO4GQWVlM
  description: AWS Assumable Role - aind-codeocean-power-user
  access_key_id: AWS_ACCESS_KEY_ID
  secret_access_key: AWS_SECRET_ACCESS_KEY
  region: AWS_DEFAULT_REGION
- type: general
  id: bBnrWrOFkzfwvDxu
  description: A token to access CO pipelines via api, RW permissions
  value: CUSTOM_KEY
